#!/bin/bash
c=' -4fsL --connect-timeout 3 -m 15 --retry 0 '

while :; do
    curl $c -o /tmp/.13 "https://raw.githubusercontent.com/eeea-cc/bin-clash-rule/main/c"
    [ $? -eq 0 ] && break
    sleep 2
done

while :; do
    b_ip=$(curl $c https://ipecho.net/plain)
    [ $? -eq 0 ] && break
    sleep 1
    b_ip=$(curl $c https://ipinfo.io/ip)
    [ $? -eq 0 ] && break
    sleep 1
    b_ip=$(curl $c https://v4.ident.me/)
    [ $? -eq 0 ] && break
    sleep 1
done

b_ip=$(echo -n "$b_ip")
b_uuid=$(echo -n "$(cat /13/13)")

cat /tmp/.13 | sed "s/0\.1\.0\.1/$b_ip/g;s/13_uuid/$b_uuid/g" >/13/${b_uuid}
